Make sonar happy and reorganization of the code [Redmine Issue #11298]
git-svn-id: http://euclid.esac.esa.int/svn/EC/SGS/SDC/CH/Projects/Elements/trunk@14701 463500fe-d6be-4184-9b20-47717e75ecac

diff --git a/ElementsKernel/scripts/addCppClass_test b/ElementsKernel/scripts/addCppClass_test
--- a/ElementsKernel/scripts/addCppClass_test
+++ b/ElementsKernel/scripts/addCppClass_test
@@ -1,5 +1,4 @@
 #!/bin/sh
-
 home_dir=${PWD}
 
 # Call common script
@@ -12,13 +11,6 @@ external_dep_name="Boost"
 # Create a unique directory
 tmploc=${TEMPORARY_LOCATION}
 
-# Clean and exit
-clean_and_exit() {
-  cd ${home_dir}
-  rm -rf ${tmploc}
-  exit $1
-}
-
 cd ${MODULE_NAME_PATH}
 
 # Create a class
@@ -26,43 +18,48 @@ AddCppClass $class_name -ed $elt_dep_name -extd $external_dep_name
 
 # if error stop and clean up
 if [ $? -ne 0 ]; then
+   echo "Error: <AddCppClass $class_name -ed $elt_dep_name -extd $external_dep_name> command failed!" 1>&2
    clean_and_exit 1
 fi
 
-
-# make sure the class files are created
+# Make sure the class files are created
 if [ ! -e "${MODULE_NAME}/${class_name}.h" ]; then
+   echo "Error: <${MODULE_NAME}/${class_name}.h> file not found!" 1>&2
    clean_and_exit 1
 fi
 if [ ! -e "src/lib/${class_name}.cpp" ]; then
    clean_and_exit 1
 fi
 
-# Make sure the elements_depends_on_subdirs Macro is there and ElementsKernel
+# Make sure the elements_depends_on_subdirs macro is there and ElementsKernel
 result=$( grep "elements_depends_on_subdirs" ${MODULE_NAME_PATH}/CMakeLists.txt |
           grep -v "#" | grep "ElementsKernel" )
 if [ $? -ne 0 ]  ;then
+   echo "Error: <elements_depends_on_subdirs> macro with <ElementsKernel> module not found!" 1>&2
    clean_and_exit 1
 fi
 
-# Make sure the elements_depends_on_subdirs Macro is there and dependency
+# Make sure the elements_depends_on_subdirs macro is there and dependency
 result=$( grep "elements_depends_on_subdirs" ${MODULE_NAME_PATH}/CMakeLists.txt |
           grep -v "#" | grep $elt_dep_name )
 if [ $? -ne 0 ]  ;then
+   echo "Error: <elements_depends_on_subdirs> macro with <$elt_dep_name> dependency not found!" 1>&2
    clean_and_exit 1
 fi
 
-# Make sure the find_package Macro is there
+# Make sure the find_package macro is there
 result=$( grep "find_package" ${MODULE_NAME_PATH}/CMakeLists.txt |
           grep -v "#" | grep $external_dep_name )
 if [ $? -ne 0 ]  ;then
+   echo "Error: find_package macro not found!" 1>&2
    clean_and_exit 1
 fi
 
-# Make sure the elements_add_library Macro is there
+# Make sure the elements_add_library macro is there
 result=$( grep "elements_add_library" ${MODULE_NAME_PATH}/CMakeLists.txt |  grep -v "#" |
           grep $module_name )
 if [ $? -ne 0 ]  ;then
+   echo "Error: <elements_add_library> macro with <$module_name> module not found!" 1>&2
    clean_and_exit 1
 fi
 
@@ -70,6 +67,7 @@ fi
 result=$( grep "LINK_LIBRARIES" ${MODULE_NAME_PATH}/CMakeLists.txt |  grep -v "#" |
           grep $elt_dep_name)
 if [ $? -ne 0 ]  ;then
+   echo "Error: LINK_LIBRARIES macro with <$elt_dep_name> Element dependency not found!" 1>&2
    clean_and_exit 1
 fi
 
@@ -77,6 +75,8 @@ fi
 result=$( grep "LINK_LIBRARIES" ${MODULE_NAME_PATH}/CMakeLists.txt |  grep -v "#" |
           grep $external_dep_name)
 if [ $? -ne 0 ]  ;then
+   echo "Error: LINK_LIBRARIES macro with <$external_dep_name> external dependency not found!" 1>&2
    clean_and_exit 1
 fi
+
 clean_and_exit 0
diff --git a/ElementsKernel/scripts/addPythonProgram_test b/ElementsKernel/scripts/addPythonProgram_test
--- a/ElementsKernel/scripts/addPythonProgram_test
+++ b/ElementsKernel/scripts/addPythonProgram_test
@@ -10,13 +10,6 @@ python_prog_name="PythonProgramTest"
 # Create a unique directory
 tmploc=${TEMPORARY_LOCATION}
 
-# Clean and exit
-clean_and_exit() {
-  cd ${home_dir}
-  rm -rf ${tmploc}
-  exit $1
-}
-
 cd ${MODULE_NAME_PATH}
 
 # Create python program
@@ -24,32 +17,39 @@ AddPythonProgram $python_prog_name
 
 # Error? stop and clean up
 if [ $? -ne 0 ]; then
+   echo "Error: <AddPythonProgram $python_prog_name> command failed!" 1>&2
    clean_and_exit 1
 fi
 
 # Make sure python files have been created
 if [ ! -e python/${MODULE_NAME}/${python_prog_name}.py ]; then
+   echo "Error: <python/${MODULE_NAME}/${python_prog_name}.py> file not found!" 1>&2
    clean_and_exit 1
 fi
+
 if [ ! -e python/${MODULE_NAME}/__init__.py ]; then
+   echo "Error: <python/${MODULE_NAME}/__init__.py> file not found!" 1>&2
    clean_and_exit 1
 fi
 
 # Make sure the <elements_install_scripts> macro is there
 result=$( grep "elements_install_scripts" CMakeLists.txt | grep -v "#")
 if [ $? -ne 0  ];then
+   echo "Error: <elements_install_scripts> macro not found!" 1>&2
    clean_and_exit 1
 fi
 
 # Make sure the <elements_install_python_modules> macro is there
 result=$( grep "elements_install_python_modules" CMakeLists.txt | grep -v "#")
 if [ $? -ne 0  ];then
+   echo "Error: <elements_install_python_modules> macro not found!" 1>&2
    clean_and_exit 1
 fi
 
-# Make sure the <elements_install_python_modules> macro is there
+# Make sure the <elements_add_python_program> macro is there
 result=$( grep "elements_add_python_program" CMakeLists.txt | grep -v "#" | grep ${python_prog_name})
 if [ $? -ne 0  ];then
+   echo "Error: <elements_add_python_program> macro and <${python_prog_name}> program not found!" 1>&2
    clean_and_exit 1
 fi
 
diff --git a/ElementsKernel/scripts/createCommonStructure_test b/ElementsKernel/scripts/createCommonStructure_test
--- a/ElementsKernel/scripts/createCommonStructure_test
+++ b/ElementsKernel/scripts/createCommonStructure_test
@@ -1,5 +1,9 @@
 #!/bin/sh
 
+# define this variable if you want to keep the tmploc directory
+# for debugging purposes
+export KEEPTEMPDIR=0
+
 home_dir=${PWD}
 
 project_name="ProjectTest"
@@ -7,12 +11,14 @@ version="1.0"
 module_name="ModuleTest"
 
 # Create unique directory
-tmploc=$(mktemp -dq -t temp.XXXXXX)
+tmploc=$(mktemp -d -t temp.XXXXXX)
 
 # Clean and exit
 clean_and_exit() {
   cd ${home_dir}
-  rm -rf ${tmploc}
+  if [ -z "${KEEPTEMPDIR}" ]; then
+    rm -rf ${tmploc}
+  fi
   exit $1
 }
 
@@ -26,6 +32,7 @@ CreateElementsProject $project_name $version
 
 # if error stop and clean up
 if [ $? -ne 0 ]; then
+   echo "Error: <CreateElementsProject $project_name $version> command failed!" 1>&2
    clean_and_exit 1
 fi
 
@@ -37,6 +44,7 @@ AddElementsModule $module_name
 
 # if error stop and clean up
 if [ $? -ne 0 ]; then
+   echo "Error: <AddElementsModule $module_name> command failed!" 1>&2
    clean_and_exit 1
 fi
 
diff --git a/ElementsKernel/scripts/createElementsProject_test b/ElementsKernel/scripts/createElementsProject_test
--- a/ElementsKernel/scripts/createElementsProject_test
+++ b/ElementsKernel/scripts/createElementsProject_test
@@ -9,7 +9,7 @@ version="1.0"
 tmploc=$(mktemp -dq -t temp.XXXXXX)
 
 # Clean and exit
-clean_and_exit() {
+local_clean_exit() {
   cd ${home_dir}
   rm -rf ${tmploc}
   exit $1
@@ -24,24 +24,28 @@ CreateElementsProject $project_name $version
 
 # Error? stop and clean up
 if [ $? -ne 0 ]; then
-   clean_and_exit 1
+   echo "Error: <CreateElementsProject $project_name $version> command failed!" 1>&2
+   local_clean_exit 1
 fi
 
 # Make sure the project has been created
 if [ ! -d $project_name ]; then
-   clean_and_exit 1
+   echo "Error: <$project_name> directory not found!" 1>&2
+   local_clean_exit 1
 fi
 
 # Make sure mandatory files has been created
 if [ ! -e $User_area/$project_name/$version/CMakeLists.txt ] ||
    [ ! -e $User_area/$project_name/$version/Makefile ]; then
-   clean_and_exit 1
+   echo "Error: <$User_area/$project_name/$version/CMakeLists.txt (and/or Makefile)> file not found" 1>&2
+   local_clean_exit 1
 fi
 
 # Make sure <Project_test> is there
 result=$( grep "$project_name $version" $User_area/$project_name/$version/CMakeLists.txt )
 if [ $? -ne 0 ]; then
-   clean_and_exit 1
+   echo "Error: <$project_name $version> not found in <$User_area/$project_name/$version/CMakeLists.txt> file!" 1>&2
+   local_clean_exit 1
 fi
 
-clean_and_exit 0
+local_clean_exit 0
