Fix test when BINARY_TAG is not in the environment

diff --git a/ElementsKernel/scripts/checkProjectDependencyFailure_test b/ElementsKernel/scripts/checkProjectDependencyFailure_test
--- a/ElementsKernel/scripts/checkProjectDependencyFailure_test
+++ b/ElementsKernel/scripts/checkProjectDependencyFailure_test
@@ -45,18 +45,16 @@ echo "CMAKE_PREFIX_PATH: ${CMAKE_PREFIX_PATH}"
 
 cd ${User_area}
 
-CreateElementsProject -s $projectA_name $projectA_version --yes
+CreateElementsProject --yes -s $projectA_name $projectA_version
 
 # Error? stop and clean up
 if [ $? -ne 0 ]; then
-   echo "Error: <CreateElementsProject -s $projectA_name $projectA_version> command failed!" 1>&2
+   echo "Error: <CreateElementsProject --yes -s $projectA_name $projectA_version> command failed!" 1>&2
    local_clean_exit 1
 fi
 
 cd $projectA_name/$projectA_version
-#AddElementsModule $projectA_name
-
-
+#AddElementsModule --yes $projectA_name
 
 make configure
 
@@ -79,9 +77,11 @@ if [ $? -ne 0 ]; then
    local_clean_exit 1
 fi
 
-if [ ! -e InstallArea/${BINARY_TAG}/manifest.xml ]; then
-   echo "Error: <Installation of $projectA_name $projectA_version> failed!" 1>&2
-   local_clean_exit 1
+if [ -n "${BINARY_TAG}" ]; then
+  if [ ! -e InstallArea/${BINARY_TAG}/manifest.xml ]; then
+    echo "Error: <Installation of $projectA_name $projectA_version> failed!" 1>&2
+    local_clean_exit 1
+  fi
 fi
 
 cd ${User_area}
@@ -118,11 +118,12 @@ if [ $? -ne 0 ]; then
    local_clean_exit 1
 fi
 
-if [ ! -e InstallArea/${BINARY_TAG}/manifest.xml ]; then
-   echo "Error: <Installation of $projectAp_name $projectAp_version> failed!" 1>&2
-   local_clean_exit 1
+if [ -n "${BINARY_TAG}" ]; then
+  if [ ! -e InstallArea/${BINARY_TAG}/manifest.xml ]; then
+     echo "Error: <Installation of $projectAp_name $projectAp_version> failed!" 1>&2
+     local_clean_exit 1
+  fi
 fi
-
 
 
 cd ${User_area}
