Added tests for the visibility

diff --git a/ElementsKernel/scripts/createElementsProject_test b/ElementsKernel/scripts/createElementsProject_test
--- a/ElementsKernel/scripts/createElementsProject_test
+++ b/ElementsKernel/scripts/createElementsProject_test
@@ -154,4 +154,15 @@ if [ $? -ne 0 ]; then
    local_clean_exit 1
 fi
 
+# Test the visibility option
+project_name="ProjectVisibilityTest"
+version="1.0"
+
+CreateElementsProject $project_name $version -V --yes
+pattern="ELEMENTS_HIDE_SYMBOLS ON"
+result=$( grep $pattern "${project_name}/${version}/CMakeLists.txt" )
+if [ $? -ne 0 ]; then
+   echo "Error: No < $pattern...etc...> pattern found in CMakeLists.txt in this <$project_name> project name!" 1>&2
+   local_clean_exit 1
+fi
 local_clean_exit 0
