Add test on the "make info" command itself

diff --git a/ElementsKernel/scripts/createDependentElementsProjects_test b/ElementsKernel/scripts/createDependentElementsProjects_test
--- a/ElementsKernel/scripts/createDependentElementsProjects_test
+++ b/ElementsKernel/scripts/createDependentElementsProjects_test
@@ -73,9 +73,29 @@ if [ ! -f build.${BINARY_TAG}/cmake_info.cmake ]; then
 fi
 
 # Make sure <ProjectA_version> is there
-result=$(grep "${projectA_version}"  build.${BINARY_TAG}/cmake_info.cmake)
+result=$(grep -F "Version: ${projectA_version}" build.${BINARY_TAG}/cmake_info.cmake)
 if [ $? -ne 0 ]; then
    echo "Error: <${projectA_version}> not found in <build.${BINARY_TAG}/cmake_info.cmake> file!" 1>&2
+   local_clean_exit 1
+fi
+
+result=$(cmake -P build.${BINARY_TAG}/cmake_info.cmake | grep -F "Version: ${projectA_version}")
+if [ $? -ne 0 ]; then
+   echo "Error: <${projectA_version}> not found in <build.${BINARY_TAG}/cmake_info.cmake> file!" 1>&2
+   local_clean_exit 1
+fi
+
+
+# Make sure <ProjectA_name> is there
+result=$(grep -F "Name: ${projectA_name}" build.${BINARY_TAG}/cmake_info.cmake)
+if [ $? -ne 0 ]; then
+   echo "Error: <${projectA_name}> not found in <build.${BINARY_TAG}/cmake_info.cmake> file!" 1>&2
+   local_clean_exit 1
+fi
+
+result=$(cmake -P build.${BINARY_TAG}/cmake_info.cmake | grep -F "Name: ${projectA_name}")
+if [ $? -ne 0 ]; then
+   echo "Error: <${projectA_name}> not found in <build.${BINARY_TAG}/cmake_info.cmake> file!" 1>&2
    local_clean_exit 1
 fi
 
