Fix 3 things: Feature #5886,#5887, Bug #5835
- Feature #5886:
Add a gitignore template for the creation script that generates an
Elements-based project
- Feature #5887
Add a --yes option to bypass the interactive part in the creation
scripts
-Bug #5835
Fix the creation script with the new localisation functions

diff --git a/ElementsKernel/scripts/createElementsProject_test b/ElementsKernel/scripts/createElementsProject_test
--- a/ElementsKernel/scripts/createElementsProject_test
+++ b/ElementsKernel/scripts/createElementsProject_test
@@ -23,9 +23,16 @@ export User_area=${tmploc}
 
 cd ${tmploc} || local_clean_exit 1
 
-CreateElementsProject $project_name $version -d $dep_project $version<<EOF
-y
-EOF
+CreateElementsProject $project_name $version -d $dep_project $version --yes
+
+# Error? stop and clean up
+if [ $? -ne 0 ]; then
+   echo "Error: <CreateElementsProject $project_name $version> command failed!" 1>&2
+   local_clean_exit 1
+fi
+
+# Test --yes option
+CreateElementsProject $project_name $version -d $dep_project $version --yes
 
 # Error? stop and clean up
 if [ $? -ne 0 ]; then
@@ -40,9 +47,16 @@ if [ ! -d $project_name ]; then
 fi
 
 # Make sure mandatory files has been created
-if [ ! -e $User_area/$project_name/$version/CMakeLists.txt ] ||
-   [ ! -e $User_area/$project_name/$version/Makefile ]; then
-   echo "Error: <$User_area/$project_name/$version/CMakeLists.txt (and/or Makefile)> file not found" 1>&2
+if [ ! -e $User_area/$project_name/$version/CMakeLists.txt ]; then
+   echo "Error: <$User_area/$project_name/$version/CMakeLists.txt> file not found" 1>&2
+   local_clean_exit 1
+fi
+if [ ! -e $User_area/$project_name/$version/.gitignore ]; then
+   echo "Error: <$User_area/$project_name/$version/.gitignore> file not found" 1>&2
+   local_clean_exit 1
+fi
+if [ ! -e $User_area/$project_name/$version/Makefile ]; then
+   echo "Error: <$User_area/$project_name/$version/Makefile> file not found" 1>&2
    local_clean_exit 1
 fi
 
@@ -62,7 +76,7 @@ fi
 
 cd ${User_area}/${project_name}/${version} || local_clean_exit 1
 
-AddElementsModule ${module_name}
+AddElementsModule ${module_name} --yes
 
 # Error? stop and clean up
 if [ $? -ne 0 ]; then
@@ -72,7 +86,7 @@ fi
 
 cd ${module_name} || local_clean_exit 1
 
-AddPythonModule ${py_module_name}
+AddPythonModule ${py_module_name} --yes
 
 # Error? stop and clean up
 if [ $? -ne 0 ]; then
@@ -87,9 +101,7 @@ cd ${tmploc} || local_clean_exit 1
 project_name="WrongProjectTest]"
 version="1.0"
 
-CreateElementsProject $project_name $version <<EOF
-y
-EOF
+CreateElementsProject $project_name $version --yes
 
 if [ $? -eq 0 ]; then
    echo "Error: this <$project_name> project name should failed but it did not!" 1>&2
@@ -103,9 +115,7 @@ cd ${tmploc} || local_clean_exit 1
 project_name="WrongProjectTest"
 version="1.0]"
 
-CreateElementsProject $project_name $version <<EOF
-y
-EOF
+CreateElementsProject $project_name $version --yes
 
 if [ $? -eq 0 ]; then
    echo "Error: this <$version> version number should failed but it did not!" 1>&2
@@ -118,9 +128,7 @@ cd ${tmploc} || local_clean_exit 1
 project_name="ProjectHeadTest"
 version="HEAD"
 
-CreateElementsProject $project_name $version <<EOF
-y
-EOF
+CreateElementsProject $project_name $version --yes
 
 if [ $? -ne 0 ]; then
    echo "Error: this <$version> version number should not failed!!!" 1>&2
