Added test units for the Elements python scripts
git-svn-id: http://euclid.esac.esa.int/svn/EC/SGS/SDC/CH/Projects/Elements/trunk@9916 463500fe-d6be-4184-9b20-47717e75ecac

diff --git a/ElementsKernel/scripts/createElementsProject_test b/ElementsKernel/scripts/createElementsProject_test
--- a/ElementsKernel/scripts/createElementsProject_test
+++ b/ElementsKernel/scripts/createElementsProject_test
@@ -1,7 +1,11 @@
 #!/bin/sh 
 
-
 home_dir=${PWD}
+
+project_name="ProjectTest"
+version="1.0"
+
+# Create unique directory 
 tmploc=$(mktemp -dq -t temp.XXXXXX)
 
 # Clean and exit
@@ -11,30 +15,32 @@ clean_and_exit() {
   exit $1
 }
 
-# Move to tmp directory
-cd ${tmploc}
+# Set to the User_area
 export User_area=${tmploc}
 
-CreateElementsProject Project_test 1.0
+cd ${tmploc}
 
-# if error stop and clean up
+CreateElementsProject $project_name $version
+
+# Error? stop and clean up
 if [ $? -ne 0 ]; then
    clean_and_exit 1
 fi
 
-# make sure project is created
-if [ ! -d Project_test ]; then
+# Make sure the project has been created
+if [ ! -d $project_name ]; then
    clean_and_exit 1
 fi
 
-# make sure project is created
-if [ ! -e $User_area/Project_test/1.0/CMakeLists.txt ] ||
-   [ ! -e $User_area/Project_test/1.0/Makefile ]; then
+# Make sure mandatory files has been created
+if [ ! -e $User_area/$project_name/$version/CMakeLists.txt ] ||
+   [ ! -e $User_area/$project_name/$version/Makefile ]; then
    clean_and_exit 1
 fi
 
-# Make sure Project_test is there
-if [ ! `grep "Project_test 1.0" $User_area/Project_test/1.0/CMakeLists.txt`  ];then
+# Make sure <Project_test> is there
+result=$( grep "$project_name $version" $User_area/$project_name/$version/CMakeLists.txt )
+if [ $? -ne 0 ]; then
    clean_and_exit 1
 fi
 
