Add tests to check for missing version in the elements_project call

diff --git a/ElementsKernel/scripts/missingElementsProjectVersion_test b/ElementsKernel/scripts/missingElementsProjectVersion_test
--- a/ElementsKernel/scripts/missingElementsProjectVersion_test
+++ b/ElementsKernel/scripts/missingElementsProjectVersion_test
@@ -18,7 +18,7 @@ tmploc=$(mktemp -dq -t temp.XXXXXX)
 # Clean and exit
 local_clean_exit() {
   cd ${home_dir}
-  #  rm -rf ${tmploc}
+  rm -rf ${tmploc}
   exit $1
 }
 
@@ -102,8 +102,6 @@ if [ $? -ne 0 ]; then
    local_clean_exit 1
 fi
 
-
-
 make
 
 if [ $? -ne 0 ]; then
@@ -132,7 +130,47 @@ CreateElementsProject -s -d $projectA_name $projectA_version $projectB_name $pro
 
 cd $projectB_name/$projectB_version
 
-make configure
+make configure > configure.log 2>&1
+
+if [ $? -ne 0 ]; then
+   echo "Error: <Configuration of $projectB_name $projectB_version> failed!" 1>&2
+   local_clean_exit 1
+fi
+
+mv CMakeLists.txt CMakeLists.txt.bck
+
+cat << EOF > CMakeLists.txt
+CMAKE_MINIMUM_REQUIRED(VERSION 2.8.5)
+
+find_package(ElementsProject)
+
+elements_project(ProjectB 1.2 USE  ProjectA)
+
+EOF
+
+make configure > configure.failed.log 2>&1
+if [ $? -eq 0 ]; then
+   echo "Error: <Configuration of $projectB_name $projectB_version> Succeeded!" 1>&2
+   local_clean_exit 1
+fi
+
+grep -q "CMake Error" configure.failed.log
+if [ $? -ne 0 ]; then
+   echo "Error: cannot find 'CMake Error' in the log file" 1>&2
+   local_clean_exit 1
+fi
+
+grep -q "No project version specified for ProjectA" configure.failed.log
+if [ $? -ne 0 ]; then
+   echo "Error: cannot find the error message in the log file" 1>&2
+   local_clean_exit 1
+fi
+
+
+rm -f CMakeLists.txt
+mv CMakeLists.txt.bck CMakeLists.txt
+rm -f configure.log
+make configure > configure.log 2>&1
 
 if [ $? -ne 0 ]; then
    echo "Error: <Configuration of $projectB_name $projectB_version> failed!" 1>&2
@@ -162,12 +200,53 @@ CreateElementsProject -s -d $projectA_name $projectA_version -d $projectB_name $
 
 cd $projectC_name/$projectC_version
 
-make configure
+make configure > configure.log 2>&1
 
 if [ $? -ne 0 ]; then
    echo "Error: <Configuration of $projectC_name $projectC_version> failed!" 1>&2
    local_clean_exit 1
 fi
+
+mv CMakeLists.txt CMakeLists.txt.bck
+
+cat << EOF > CMakeLists.txt
+CMAKE_MINIMUM_REQUIRED(VERSION 2.8.5)
+
+find_package(ElementsProject)
+
+elements_project(ProjectC 1.3 USE ProjectA ProjectB 1.2)
+                                                                                                         
+EOF
+
+make configure > configure.failed.log 2>&1
+if [ $? -eq 0 ]; then
+   echo "Error: <Configuration of $projectC_name $projectC_version> Succeeded!" 1>&2
+   local_clean_exit 1
+fi
+
+grep -q "CMake Error" configure.failed.log
+if [ $? -ne 0 ]; then
+   echo "Error: cannot find 'CMake Error' in the log file" 1>&2
+   local_clean_exit 1
+fi
+
+grep -q "ProjectB is not a version" configure.failed.log
+if [ $? -ne 0 ]; then
+   echo "Error: cannot find the error message in the log file" 1>&2
+   local_clean_exit 1
+fi
+
+
+rm -f CMakeLists.txt
+mv CMakeLists.txt.bck CMakeLists.txt
+rm -f configure.log
+make configure > configure.log 2>&1
+
+if [ $? -ne 0 ]; then
+   echo "Error: <Configuration of $projectC_name $projectC_version> failed!" 1>&2
+   local_clean_exit 1
+fi
+
 
 make
 
