Fix CMake warnings

diff --git a/ElementsKernel/scripts/squeezedInstall_test b/ElementsKernel/scripts/squeezedInstall_test
--- a/ElementsKernel/scripts/squeezedInstall_test
+++ b/ElementsKernel/scripts/squeezedInstall_test
@@ -30,8 +30,6 @@ unset ELEMENTSSERVICESROOT
 unset ELEMENTS_NAMING_DB_URL
 unset ELEMENTS_PROJECT_ROOT
 
-printenv | grep -i make
-
 # Configure Elements
 elements_build_dir=${tmploc}/ElementsBuild
 mkdir -p ${elements_build_dir}
@@ -39,30 +37,30 @@ cd ${elements_build_dir}
 cmake -DCMAKE_PREFIX_PATH=${custom_prefix} -DCMAKE_INSTALL_PREFIX=${custom_prefix} ${ELEMENTS_SOURCE_DIR}
 if [ $? -ne 0 ]; then
   echo "Error: <cmake -DCMAKE_PREFIX_PATH=${custom_prefix} -DCMAKE_INSTALL_PREFIX=${custom_prefix} ${ELEMENTS_SOURCE_DIR}> command failed!" 1>&2
-   local_clean_exit 1
+  local_clean_exit 1
 fi
 
 
 # Build Elements
 make
 if [ $? -ne 0 ]; then
-   echo "Error: <make> command failed!" 1>&2
-   local_clean_exit 1
+  echo "Error: <make> command failed!" 1>&2
+  local_clean_exit 1
 fi
 
 # Run Elements Tests (exclude this one)
 ctest -T test -E ElementsKernel.SqueezedInstall
 if [ $? -ne 0 ]; then
-   echo "Error: <ctest -T -E ElementsKernel.SqueezedInstall> command failed!" 1>&2
-   local_clean_exit 1
+  echo "Error: <ctest -T -E ElementsKernel.SqueezedInstall> command failed!" 1>&2
+  local_clean_exit 1
 fi
 
 
 # Install Elements
 make install
 if [ $? -ne 0 ]; then
-   echo "Error: <make install> command failed!" 1>&2
-   local_clean_exit 1
+  echo "Error: <make install> command failed!" 1>&2
+  local_clean_exit 1
 fi
 
 
